name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.11.4]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install meteorjs
      run: |
        if [[ -f ~/.meteor/meteor ]]; then \
          printf "\nMeteor already installed. Creating symlink.\n"
          sudo ln -s ~/.meteor/meteor /usr/local/bin/meteor;
        else
          printf "\Installing Meteor\n"
          curl https://install.meteor.com | /bin/sh
        fi
    - name: install deps
      run: |
        meteor npm install
    - name: test
      run: |
        meteor test --once --driver-package meteortesting:mocha
      env:
        CI: true

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tideflowio/tideflow
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
